// 파라미터 및 필드 라벨 정의
import type { LocalizedLabel } from '../types';

// 파라미터 라벨 (한글/영어)
export const PARAM_LABELS: Record<string, LocalizedLabel> = {
  'I_LIFNR': { ko: '업체코드', en: 'Vendor' },
  'I_WERKS': { ko: '공장', en: 'Plant' },
  'I_BUDAT': { ko: '기준일자', en: 'Base Date' },
  'I_SPMON': { ko: '기준월', en: 'Base Month' },
  'I_ZDSEND2_START': { ko: '전표일자', en: 'Doc Date' },
  'I_DISPD': { ko: '일별기준일', en: 'Daily Date' },
  'I_DISPW': { ko: '기준월요일', en: 'Base Monday' },
  'I_ZPLDAYS': { ko: '계획일수', en: 'Plan Days' },
  'I_ERDAT': { ko: '생성일자', en: 'Create Date' },
  'I_ZASNNO': { ko: 'ASN번호', en: 'ASN No' },
  'I_STATUS': { ko: '상태', en: 'Status' },
  'I_BASEDT': { ko: '기준일자', en: 'Base Date' },
  'I_MATNR': { ko: '자재번호', en: 'Material' },
};

// API 응답 필드 라벨 (한글/영어)
export const FIELD_LABELS: Record<string, LocalizedLabel> = {
  // 공통
  'MATNR': { ko: '자재번호', en: 'Material No' },
  'MAKTX': { ko: '자재명', en: 'Material Name' },
  'LIFNR': { ko: '업체코드', en: 'Vendor Code' },
  'NAME1': { ko: '업체명', en: 'Vendor Name' },
  'WERKS': { ko: '공장', en: 'Plant' },
  'LGORT': { ko: '저장위치', en: 'Storage Loc' },
  'MEINS': { ko: '단위', en: 'Unit' },
  'MENGE': { ko: '수량', en: 'Quantity' },
  'NETPR': { ko: '단가', en: 'Unit Price' },
  'WAERS': { ko: '통화', en: 'Currency' },
  'BUDAT': { ko: '전기일', en: 'Posting Date' },
  'BLDAT': { ko: '증빙일', en: 'Document Date' },
  'EBELN': { ko: '구매문서', en: 'PO Number' },
  'EBELP': { ko: '구매항목', en: 'PO Item' },
  'BELNR': { ko: '전표번호', en: 'Document No' },
  'BUZEI': { ko: '전표항목', en: 'Doc Item' },
  'GJAHR': { ko: '회계연도', en: 'Fiscal Year' },
  'BUKRS': { ko: '회사코드', en: 'Company Code' },
  // 품목정보
  'MATKL': { ko: '자재그룹', en: 'Material Group' },
  'MTART': { ko: '자재유형', en: 'Material Type' },
  'BRGEW': { ko: '중량', en: 'Weight' },
  'GEWEI': { ko: '중량단위', en: 'Weight Unit' },
  'GROES': { ko: '규격', en: 'Size/Spec' },
  'NORMT': { ko: '도번', en: 'Drawing No' },
  'DATBI': { ko: '유효종료일', en: 'Valid To' },
  'DATAB': { ko: '유효시작일', en: 'Valid From' },
  'DISPO': { ko: 'MRP담당자', en: 'MRP Controller' },
  'LGPBE': { ko: '저장위치', en: 'Storage Bin' },
  'MDV01': { ko: '공급업체', en: 'Supplier' },
  // 커스텀 필드
  'ZCDVIS': { ko: '가시성', en: 'Visibility' },
  'ZCSNACGN': { ko: 'SNA코드', en: 'SNA Code' },
  'ZCLOGRPL': { ko: '물류대체', en: 'Log Replace' },
  'ZCALC_CD': { ko: '계산코드', en: 'Calc Code' },
  'ZCLSTY': { ko: '분류유형', en: 'Class Type' },
  'ZQCONST': { ko: '수량상수', en: 'Qty Const' },
  'ZCCASNO': { ko: 'CAS번호', en: 'CAS No' },
  'ZQPERCS': { ko: '백분율', en: 'Percentage' },
  'ZCPGATE': { ko: '게이트', en: 'Gate' },
  'ZCCYCGN': { ko: '사이클', en: 'Cycle' },
  'ZCGRTY': { ko: '그룹유형', en: 'Group Type' },
  'ZCCAR': { ko: '차종', en: 'Car Type' },
  'ZCQATY': { ko: '수량유형', en: 'Qty Type' },
  // 입출고
  'MBLNR': { ko: '자재문서', en: 'Material Doc' },
  'ZEILE': { ko: '자재항목', en: 'Material Item' },
  'BWART': { ko: '이동유형', en: 'Movement Type' },
  'SHKZG': { ko: '차변/대변', en: 'Debit/Credit' },
  'DMBTR': { ko: '금액', en: 'Amount' },
  'ERFMG': { ko: '입고수량', en: 'GR Quantity' },
  'ERFME': { ko: '입고단위', en: 'GR Unit' },
  // 소요량
  'BDMNG': { ko: '소요량', en: 'Requirement' },
  'BDTER': { ko: '소요일', en: 'Req Date' },
  'PLNUM': { ko: '계획번호', en: 'Plan Number' },
  'DISPD': { ko: '기준일', en: 'Base Date' },
  // ASN/출하
  'ZASNNO': { ko: 'ASN번호', en: 'ASN Number' },
  'ZNDONO': { ko: '납품번호', en: 'Delivery No' },
  'ERDAT': { ko: '생성일', en: 'Created Date' },
  'ERZET': { ko: '생성시간', en: 'Created Time' },
  'ERNAM': { ko: '생성자', en: 'Created By' },
  // 재고
  'LABST': { ko: '가용재고', en: 'Available Stock' },
  'INSME': { ko: '검사재고', en: 'QI Stock' },
  'SPEME': { ko: '보류재고', en: 'Blocked Stock' },
  'GESME': { ko: '총재고', en: 'Total Stock' },
  // 정산
  'SPMON': { ko: '정산월', en: 'Settlement Month' },
  'NETWR': { ko: '정산금액', en: 'Net Amount' },
  'ZRETRO': { ko: '소급금액', en: 'Retro Amount' },
  // 기타
  'ZSTATUS': { ko: '상태', en: 'Status' },
  'ZMSG': { ko: '메시지', en: 'Message' },
  'ZRESULT': { ko: '결과', en: 'Result' },
  // 추가 필드
  'ZPNTNM': { ko: '공장명', en: 'Plant Name' },
  'ZCSHOP': { ko: 'Shop', en: 'Shop' },
  'ZCLLC': { ko: 'LLC', en: 'LLC' },
  'ZQMITU': { ko: 'MITU 재고', en: 'MITU Stock' },
  'ZQWBS': { ko: 'WBS 재고', en: 'WBS Stock' },
  'ZQPRJ': { ko: 'PRJ 재고', en: 'PRJ Stock' },
  'ZQPBS': { ko: 'PBS 재고', en: 'PBS Stock' },
  'ZQWIP': { ko: 'WIP 재고', en: 'WIP Stock' },
  'ZDATFM': { ko: '시작일', en: 'From Date' },
  'ZDATTO': { ko: '종료일', en: 'To Date' },
  'ZWKFM': { ko: '시작주차', en: 'From Week' },
  'ZWKTO': { ko: '종료주차', en: 'To Week' },
  'ZASNTY': { ko: 'ASN유형', en: 'ASN Type' },
  'ZASNSEQ': { ko: 'ASN순번', en: 'ASN Seq' },
  'ZDIVNO': { ko: '분할번호', en: 'Div No' },
  'WEMNG': { ko: '입고수량', en: 'GR Qty' },
  'WAMNG': { ko: '입고예정수량', en: 'GR Plan Qty' },
  'ZGRMENGE': { ko: '입고량', en: 'GR Amount' },
  'ZDLMENGE': { ko: '납품수량', en: 'Delivery Qty' },
  'ZDARR': { ko: '도착일', en: 'Arrival Date' },
  'ZQARR1': { ko: '도착수량', en: 'Arrival Qty' },
  'ZAWZUBB': { ko: '불량수량', en: 'Defect Qty' },
  'GRUND': { ko: '사유코드', en: 'Reason Code' },
  'LFSNR': { ko: '납품서번호', en: 'Delivery Note' },
  'REFLFSPOS': { ko: '납품서항목', en: 'DN Item' },
  'ZDSEND2': { ko: '전표일자', en: 'Doc Date' },
  'ZDSTRIN': { ko: '입고일시', en: 'GR DateTime' },
  'ZLABST': { ko: '가용재고', en: 'Avail Stock' },
  'ZLABST_A': { ko: 'A재고', en: 'Stock A' },
  'ZLABST_P': { ko: 'P재고', en: 'Stock P' },
  'ZLABST_W': { ko: 'W재고', en: 'Stock W' },
  'ZLABST_ALL': { ko: '전체재고', en: 'Total Stock' },
  'ZLABST_PHY': { ko: '실물재고', en: 'Physical Stock' },
  'QTY_PHYSICAL': { ko: '실물수량', en: 'Physical Qty' },
  'QTY_WH': { ko: '창고수량', en: 'WH Qty' },
  'QTY_BASEDT': { ko: '기준일수량', en: 'Base Qty' },
  'QTY_COUNT': { ko: '실사수량', en: 'Count Qty' },
  'QTY_D1': { ko: 'D+1수량', en: 'D+1 Qty' },
  'QTY_D2': { ko: 'D+2수량', en: 'D+2 Qty' },
  'QTY_D3': { ko: 'D+3수량', en: 'D+3 Qty' },
  'QTY_D4': { ko: 'D+4수량', en: 'D+4 Qty' },
  'QTY_ADJ': { ko: '조정수량', en: 'Adj Qty' },
  'ZDIFF_QTY': { ko: '차이수량', en: 'Diff Qty' },
  'ZDAMAGE_QTY': { ko: '손상수량', en: 'Damage Qty' },
  'ZOTHER_QTY': { ko: '기타수량', en: 'Other Qty' },
  'ZPROD_QTY': { ko: '생산수량', en: 'Prod Qty' },
  'ZCLV': { ko: '레벨', en: 'Level' },
  'ZCINDLGN': { ko: '입고지시', en: 'GR Instr' },
  'ZCINSHOP': { ko: '입고Shop', en: 'GR Shop' },
  'ZCOCR': { ko: '소급구분', en: 'Retro Type' },
  'ZCFLAG': { ko: '플래그', en: 'Flag' },
  'ZCSOURCE': { ko: '소스', en: 'Source' },
  'ZCDE': { ko: '내수/수출', en: 'Dom/Exp' },
  'ZCDOC': { ko: '문서유형', en: 'Doc Type' },
  'ZCFDR': { ko: 'FDR', en: 'FDR' },
  'ZCHDPOGB': { ko: '발주구분', en: 'PO Type' },
  'ZANETPR': { ko: '단가', en: 'Unit Price' },
  'ZAPIMAMT': { ko: '금액', en: 'Amount' },
  'ZAOCKEA': { ko: '원가EA', en: 'Cost/EA' },
  'ZAOCL': { ko: '원가L', en: 'Cost L' },
  'ZAOCV': { ko: '원가V', en: 'Cost V' },
  'ZQOCL': { ko: '수량L', en: 'Qty L' },
  'ZQOCV': { ko: '수량V', en: 'Qty V' },
  'ZABSGAM': { ko: '절대금액', en: 'Abs Amount' },
  'EINDT': { ko: '납기일', en: 'Delivery Date' },
  'ZDEPDAT': { ko: '출발일', en: 'Depart Date' },
  'ZDEPTIM': { ko: '출발시간', en: 'Depart Time' },
  'ZEARDAT': { ko: '도착예정일', en: 'ETA Date' },
  'ZEARTIM': { ko: '도착예정시간', en: 'ETA Time' },
  'ZTCYTIM': { ko: '사이클타임', en: 'Cycle Time' },
  'E_DATAB': { ko: '유효시작일', en: 'Valid From' },
  'E_DATBI': { ko: '유효종료일', en: 'Valid To' },
  'ZDFRTA': { ko: '출발RTA', en: 'Depart RTA' },
  'ZDTRTA': { ko: '도착RTA', en: 'Arrival RTA' },
  'ZDLRMOBL': { ko: '차량번호', en: 'Vehicle No' },
  'ZDLRNAME': { ko: '운전자', en: 'Driver' },
  'ZDLTLOC': { ko: '납품장소', en: 'Delivery Loc' },
  'ZCTAG_CO': { ko: '태그회사', en: 'Tag Company' },
  'ZCARNO': { ko: '차량번호', en: 'Car No' },
  'ZNDONUM': { ko: '간판번호', en: 'Kanban No' },
  'ZNDOSEQ': { ko: '간판순번', en: 'Kanban Seq' },
  'BSART': { ko: '발주유형', en: 'PO Type' },
  'TXZ01': { ko: '품목내역', en: 'Item Text' },
  'VBELN': { ko: '판매문서', en: 'Sales Doc' },
  'ZNLLCVR': { ko: 'LLC버전', en: 'LLC Ver' },
  'ZNLLCNR': { ko: 'LLC번호', en: 'LLC No' },
  'ZQLLCOP': { ko: 'LLC OP', en: 'LLC OP' },
  'ZQLLCIS': { ko: 'LLC IS', en: 'LLC IS' },
  'ZQPKQTY': { ko: '포장수량', en: 'Pack Qty' },
  'ZQRINERWT': { ko: '순중량', en: 'Net Weight' },
  'ZADUNPL': { ko: '조정단위L', en: 'Adj Unit L' },
  'ZADUNPV': { ko: '조정단위V', en: 'Adj Unit V' },
  'ZEMSG': { ko: '에러메시지', en: 'Error Msg' },
  'ZREMARK': { ko: '비고', en: 'Remark' },
  'STATUS': { ko: '상태', en: 'Status' },
  'STATUS_NM': { ko: '상태명', en: 'Status Name' },
  'LOEKZ': { ko: '삭제표시', en: 'Del Flag' },
  'ELIKZ': { ko: '완료표시', en: 'Complete' },
  'MBLPO': { ko: '자재문서항목', en: 'Mat Doc Item' },
  'MJAHR': { ko: '자재문서년도', en: 'Mat Doc Year' },
  'LGOBE': { ko: '저장위치명', en: 'Storage Loc Name' },
  'ZDLBOX': { ko: '박스수량', en: 'Box Qty' },
  // 주별소요량 (ZQW01~ZQW52)
  ...generateWeeklyLabels(),
  // 일별소요량 (ZQD001~ZQD150)
  ...generateDailyLabels(),
};

// 주별 라벨 생성 함수
function generateWeeklyLabels(): Record<string, LocalizedLabel> {
  const labels: Record<string, LocalizedLabel> = {};
  for (let i = 1; i <= 52; i++) {
    const key = `ZQW${i.toString().padStart(2, '0')}`;
    labels[key] = { ko: `W+${i}주`, en: `W+${i}` };
  }
  return labels;
}

// 일별 라벨 생성 함수
function generateDailyLabels(): Record<string, LocalizedLabel> {
  const labels: Record<string, LocalizedLabel> = {};
  for (let i = 1; i <= 150; i++) {
    const key = `ZQD${i.toString().padStart(3, '0')}`;
    labels[key] = { ko: `D+${i}`, en: `D+${i}` };
  }
  return labels;
}
