// 공장 목록 정의
import type { PlantDefinition } from '../types';

export const HMC_PLANTS: PlantDefinition[] = [
  { code: '', name: { ko: '전체', en: 'All' } },
  { code: '1000', name: { ko: 'HMC 본사', en: 'HMC HQ' } },
  { code: '1011', name: { ko: '울산 완성차 1공장', en: 'Ulsan Vehicle P1' } },
  { code: '1012', name: { ko: '울산 완성차 2공장', en: 'Ulsan Vehicle P2' } },
  { code: '1013', name: { ko: '울산 완성차 3공장', en: 'Ulsan Vehicle P3' } },
  { code: '1014', name: { ko: '울산 완성차 4공장', en: 'Ulsan Vehicle P4' } },
  { code: '1015', name: { ko: '울산 완성차 5공장', en: 'Ulsan Vehicle P5' } },
  { code: '101A', name: { ko: '울산 EV 공장', en: 'Ulsan EV Plant' } },
  { code: '1019', name: { ko: '울산 TSD 공장', en: 'Ulsan TSD Plant' } },
  { code: '1021', name: { ko: '아산 완성차 공장', en: 'Asan Vehicle' } },
  { code: '1031', name: { ko: '전주 완성차 공장', en: 'Jeonju Vehicle' } },
  { code: '1041', name: { ko: 'GGM 광주 완성차', en: 'GGM Gwangju' } },
  { code: '1070', name: { ko: '울산 엔진 공장', en: 'Ulsan Engine' } },
  { code: '1071', name: { ko: '아산 엔진 공장', en: 'Asan Engine' } },
  { code: '1072', name: { ko: '전주 엔진 공장', en: 'Jeonju Engine' } },
  { code: '1073', name: { ko: '울산 변속기 공장', en: 'Ulsan Trans' } },
  { code: '1074', name: { ko: '울산 소재 공장', en: 'Ulsan Material' } },
  { code: '1075', name: { ko: '아산 소재 공장', en: 'Asan Material' } },
  { code: '1076', name: { ko: '전주 소재 공장', en: 'Jeonju Material' } },
  { code: '1077', name: { ko: '울산 시트 1/2공장', en: 'Ulsan Seat P1/2' } },
  { code: '1078', name: { ko: '울산 시트 3공장', en: 'Ulsan Seat P3' } },
  { code: '1079', name: { ko: '충주 수소연료전지', en: 'Chungju Fuel Cell' } },
  { code: '1081', name: { ko: '울산 KD 포장공장', en: 'Ulsan KD Pack' } },
  { code: '1082', name: { ko: '아산 KD 포장공장', en: 'Asan KD Pack' } },
  { code: '1083', name: { ko: '전주 KD 포장공장', en: 'Jeonju KD Pack' } },
  { code: '1091', name: { ko: '울산 제품2 공장', en: 'Ulsan Product2' } },
  { code: '1092', name: { ko: '울산 공통 공장', en: 'Ulsan Common' } },
  { code: '1093', name: { ko: '아산 공통 공장', en: 'Asan Common' } },
  { code: '1094', name: { ko: '전주 공통 공장', en: 'Jeonju Common' } },
];

export const KMC_PLANTS: PlantDefinition[] = [
  { code: '', name: { ko: '전체', en: 'All' } },
  { code: '2900', name: { ko: 'Kia 공통', en: 'Kia Common' } },
  { code: '2911', name: { ko: '광명 완성차 1공장', en: 'Gwangmyeong P1' } },
  { code: '2912', name: { ko: '광명 EVO Plant', en: 'Gwangmyeong EVO' } },
  { code: '2921', name: { ko: '화성 완성차 1공장', en: 'Hwaseong P1' } },
  { code: '2922', name: { ko: '화성 완성차 2공장', en: 'Hwaseong P2' } },
  { code: '2923', name: { ko: '화성 완성차 3공장', en: 'Hwaseong P3' } },
  { code: '2924', name: { ko: '화성 EVO East', en: 'Hwaseong EVO E' } },
  { code: '2925', name: { ko: '화성 EVO West', en: 'Hwaseong EVO W' } },
  { code: '2931', name: { ko: '광주 완성차 1공장', en: 'Gwangju P1' } },
  { code: '2932', name: { ko: '광주 완성차 2공장', en: 'Gwangju P2' } },
  { code: '2933', name: { ko: '광주 완성차 3공장', en: 'Gwangju P3' } },
  { code: '2934', name: { ko: '광주 완성차 버스', en: 'Gwangju Bus' } },
  { code: '2935', name: { ko: '광주 완성차 군수', en: 'Gwangju Military' } },
  { code: '2941', name: { ko: 'DH 서산 완성차', en: 'DH Seosan' } },
  { code: '2971', name: { ko: '광명 엔진 공장', en: 'Gwangmyeong Engine' } },
  { code: '2972', name: { ko: '화성 엔진 공장', en: 'Hwaseong Engine' } },
  { code: '2973', name: { ko: '화성 변속기 공장', en: 'Hwaseong Trans' } },
  { code: '2974', name: { ko: '화성 소재 공장', en: 'Hwaseong Material' } },
  { code: '2975', name: { ko: '광주 소재 공장', en: 'Gwangju Material' } },
  { code: '2981', name: { ko: '화성 KD 포장공장', en: 'Hwaseong KD Pack' } },
  { code: '2982', name: { ko: '광주 KD 포장공장', en: 'Gwangju KD Pack' } },
  { code: '2983', name: { ko: '광주 KD 상용', en: 'Gwangju KD Comm' } },
  { code: '2984', name: { ko: '광주 KD 버스', en: 'Gwangju KD Bus' } },
  { code: '2985', name: { ko: '화성 KD 특수', en: 'Hwaseong KD Spec' } },
  { code: '2991', name: { ko: '광명 공통 공장', en: 'Gwangmyeong Common' } },
  { code: '2992', name: { ko: '화성 공통 공장', en: 'Hwaseong Common' } },
  { code: '2993', name: { ko: '광주 공통 공장', en: 'Gwangju Common' } },
  { code: '2994', name: { ko: 'DH 서산 공통', en: 'DH Seosan Common' } },
  { code: '2995', name: { ko: '광명 제품2 공장', en: 'Gwangmyeong Product2' } },
];
